services:
  - type: web
    name: yokeair-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: your-mongodb-database-name
          property: connectionString
      - key: PORT
        value: 5001 