services:
  - type: web
    name: yokeair-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://admin:kreshnik12345@cluster0.7mtse.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 5001

